language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
  - 9
  - 10
after_success:
  - npm install --no-save semantic-release-tamia
  - npx semantic-release --analyze-commits semantic-release-tamia/analyzeCommits --verify-release semantic-release-tamia/verifyRelease --generate-notes semantic-release-tamia/generateNotes
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
